feat(tls): dockerize app and add tls security
      - dockerize backend
      - dockerize frontend
      - add a nginx reverse proxy in front of app
      - segregate frontend, backend and postgres in isolated docker network
      - create mise tasks to deploy dockerized app

diff --git a/.mise/tasks/prepare b/.mise/tasks/prepare
--- a/.mise/tasks/prepare
+++ b/.mise/tasks/prepare
@@ -3,8 +3,26 @@
 
 set -e
 
+prerequisites=(
+    "python3" 
+    "pip" 
+    "docker"
+    # frontend 
+    "npm" 
+    "node"
+    # backend
+    "mvn" 
+    "java"
+)
+
+for cmd in "${prerequisites[@]}"; do
+    if ! command -v $cmd &> /dev/null; then
+        echo "❌ $cmd could not be found. Please install $cmd."
+        exit 1
+    fi
+done
+
 echo "Installing dependencies..."
 pip install --upgrade pip
 pip install -r requirements.txt
-
 echo "✓ Dependencies installed!"
